### ISSUE TITLE
It's not clear how we can build `textbook/interpreter`

### ISSUE THREAD

**Issue by aviatesk** [kuis-isle3sw/IoPLMaterials#68] opened 2022-05-13 02:30 UTC
It might be more useful if we can clarify the procedures expected by this README description, especially for the sake of those who are not too familiar with OCaml toolings:
> 落ちてきたソースコード中の textbook/interpreter/ ディレクトリの中にインタプリタのソースコードが入っているので，duneコマンドでビルドしましょう．

What the exact command is expected by this description?
I gave several commands a try, but didn't succeed in the build.

> from `IoPLMaterials/`
```
~/IoPLMaterials master*
❯ dune build
Error: I cannot find the root of the current workspace/project.
If you would like to create a new dune project, you can type:

    dune init project NAME

Otherwise, please make sure to run dune inside an existing project or
workspace. For more information about how dune identifies the root of the
current workspace/project, please refer to
https://dune.readthedocs.io/en/stable/usage.html#finding-the-root

~/IoPLMaterials master*
❯ dune init project textbook/interpreter/
# generates some files that seem to be unexpected?

(manual clean up)

~/IoPLMaterials master*
❯ cd textbook/interpreter 

~/IoPLMaterials/textbook/interpreter master*
❯ dune build       
Entering directory '/Users/aviatesk/IoPLMaterials/textbook'
File "interpreter/miniml.opam", line 1, characters 0-0:
Error: This opam file doesn't have a corresponding (package ...) stanza in
the dune-project_file. Since you have at least one other (package ...) stanza
in your dune-project file, you must a (package ...) stanza for each opam
package in your project.
```

**Comment by silloi** [comment] 2022-05-14 05:00
@aviatesk

Thank you for your opening an issue.

It seems that textbook/interpreter lacks something to our latest dune.
Adding dune-project file generated when `dune init project` with `(using menhir 2.1)` works to me, but I have no idea how it works (or does not work).

https://dune.readthedocs.io/en/stable/dune-files.html#dune-project-1

**Comment by smorimoto** [comment] 2022-05-14 15:06
The problem here is that the `dune-project` file is missing in the interpreter directory. There are some possible solutions, but none of them were very nice to me, so I raised the PR #70. It doesn't exactly synchronize with the textbook, but at least if you're just building code, using that branch isn't a bad idea.

**Comment by sisshiki1969** [comment] 2022-05-15 12:06
It seems that a recent release of dune requires `dune-project` file in the project root directory.

A work-around is:

1) Make a file with a content below.
```
(lang dune 3.0)
(name miniml)
(using menhir 2.1)
```

2) Save the file under `/textbook/interpreter` directory as `dune-project`.

I confirmed this works well with the latest release of dune(ver 3.1.1).

**Comment by aviatesk** [comment] 2022-05-17 10:40
Thanks so much @sisshiki1969 , I just confirmed it worked very well for me.
Do you want to open a PR on this? Otherwise I will make up a PR to include that `dune-project` file setup as well as update the README description.

**Comment by sisshiki1969** [comment] 2022-05-20 03:48
@aviatesk @smorimoto 
I got a reply from @ksuenaga.

He really appreciates @smorimoto 's PRs, but #71 is a bit of a big change and #70 depends on it, so he does not have enough time to investigate the proposals (probably after summer, he says).  Currently, he is super busy with his university work.

And he also think it would be extremely helpful, if some one could make a simple PR that would allow us to build textbook/interpreter as a work around for now, 
@aviatesk, could you please make PR for that?

**Comment by ksuenaga** [comment] 2022-05-25 23:30
Thanks all!  I merged #72.

**Closed** 2022-05-25 23:29 UTC

**Comment by smorimoto** [comment] 2024-07-04 14:28
Sorry for the late reply. The latest opam 2.2 makes setting up a development environment a lot easier and I came back here because it's time to revisit the PR I opened before.

**Comment by smorimoto** [comment] 2024-07-04 14:29
@ksuenaga The total diff is now much smaller. This should allow you to complete the review in almost just a few minutes. (Most of them are file relocation!)
